name: "e2e" # workflow name
on: [push]  # Event that will execute the workflow
jobs:  # Job (a set of steps we want to be executed)
  test-e2e:  # Job id
    name: Run E2E tests  # Job name
    runs-on: ubuntu-20.04
    steps: 
      # Stuff we want to be utilized before executing the steps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # Set of steps we want to be executed
      - name: Install dependencies  # Step name
        run: npm ci                 # Step action
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run yourt tests
        run: npx playwright test tests/home_pom.spec.ts
      - name: Upload test results  # Integrates the test results report
        # "Always" to generate the test results always
        if: always()  
        uses: actions/upload-artifact@v2
        with:
          name: TestResults  # Artifact name
          path: test-results  # path (folder) where the test results will be obtained of